package DataDictionaryLan.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import jetbrains.mps.smodel.runtime.ConstraintFunction;
import jetbrains.mps.smodel.runtime.ConstraintContext_CanBeParent;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.runtime.CheckingNodeContext;
import org.jetbrains.mps.openapi.model.SNode;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import org.jetbrains.mps.openapi.language.SContainmentLink;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.smodel.SNodePointer;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class AndConstraint_Constraints extends BaseConstraintsDescriptor {
  public AndConstraint_Constraints() {
    super(CONCEPTS.AndConstraint$Yk);
  }

  @Override
  protected ConstraintFunction<ConstraintContext_CanBeParent, Boolean> calculateCanBeParentConstraint() {
    return new ConstraintFunction<ConstraintContext_CanBeParent, Boolean>() {
      @NotNull
      public Boolean invoke(@NotNull ConstraintContext_CanBeParent context, @Nullable CheckingNodeContext checkingNodeContext) {
        boolean result = staticCanBeAParent(context.getNode(), context.getChildNode(), context.getChildConcept(), context.getLink());

        if (!(result) && checkingNodeContext != null) {
          checkingNodeContext.setBreakingNode(canBeParentBreakingPoint);
        }

        return result;
      }
    };
  }
  private static boolean staticCanBeAParent(SNode node, SNode childNode, SAbstractConcept childConcept, SContainmentLink link) {
    if (SNodeOperations.getConcept(SLinkOperations.getTarget(node, LINKS.constraint1$grtL)).equals(CONCEPTS.NotNulConstraint$7P)) {
      if (SNodeOperations.getConcept(SLinkOperations.getTarget(node, LINKS.constraint2$grVN)).equals(CONCEPTS.NotNulConstraint$7P)) {
        return false;
      }
    }
    return true;
  }
  private static final SNodePointer canBeParentBreakingPoint = new SNodePointer("r:39af35bd-6035-49b4-8b40-6f8b9f67bec2(DataDictionaryLan.constraints)", "5366905740652115841");

  private static final class CONCEPTS {
    /*package*/ static final SConcept AndConstraint$Yk = MetaAdapterFactory.getConcept(0xc2fcd0fd4f134552L, 0x8306bb0d4f1a7057L, 0x4a7b14560692eefcL, "DataDictionaryLan.structure.AndConstraint");
    /*package*/ static final SConcept NotNulConstraint$7P = MetaAdapterFactory.getConcept(0xc2fcd0fd4f134552L, 0x8306bb0d4f1a7057L, 0x4a7b145606786d19L, "DataDictionaryLan.structure.NotNulConstraint");
  }

  private static final class LINKS {
    /*package*/ static final SContainmentLink constraint1$grtL = MetaAdapterFactory.getContainmentLink(0xc2fcd0fd4f134552L, 0x8306bb0d4f1a7057L, 0x4a7b14560692eef4L, 0x4a7b14560692eef6L, "constraint1");
    /*package*/ static final SContainmentLink constraint2$grVN = MetaAdapterFactory.getContainmentLink(0xc2fcd0fd4f134552L, 0x8306bb0d4f1a7057L, 0x4a7b14560692eef4L, 0x4a7b14560692eef8L, "constraint2");
  }
}
