package DataDictionaryLan.actions;

/*Generated by MPS */

import jetbrains.mps.openapi.actions.descriptor.NodeFactory;
import org.jetbrains.mps.openapi.model.SNode;
import org.jetbrains.mps.openapi.model.SModel;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import DataDictionaryLan.behavior.StructureDefinition__BehaviorDescriptor;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SProperty;

public class node_factories_Field {
  public static class NodeFactory_5366905740651020559 implements NodeFactory {
    public void setup(SNode newNode, SNode sampleNode, SNode enclosingNode, int index, SModel model) {
      SNode nodeSd = SNodeOperations.getNodeAncestor(enclosingNode, CONCEPTS.StructureDefinition$jy, false, false);
      SPropertyOperations.assign(newNode, PROPS.name$MnvL, "Polje:" + ((int) StructureDefinition__BehaviorDescriptor.getFieldCount_idvB_NbVejpE.invoke(nodeSd) + 1));
    }
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept StructureDefinition$jy = MetaAdapterFactory.getConcept(0xc2fcd0fd4f134552L, 0x8306bb0d4f1a7057L, 0x4a7b1456067f55f1L, "DataDictionaryLan.structure.StructureDefinition");
  }

  private static final class PROPS {
    /*package*/ static final SProperty name$MnvL = MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name");
  }
}
