package DataDictionaryLan.behavior;

/*Generated by MPS */

import jetbrains.mps.core.aspects.behaviour.BaseBehaviorAspectDescriptor;
import jetbrains.mps.core.aspects.behaviour.api.BHDescriptor;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.lang.smodel.ConceptSwitchIndex;
import jetbrains.mps.lang.smodel.ConceptSwitchIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;

public final class BehaviorAspectDescriptor extends BaseBehaviorAspectDescriptor {
  private final BHDescriptor myStructure__BehaviorDescriptor = new Structure__BehaviorDescriptor();
  private final BHDescriptor mySemanticDomainDefinition__BehaviorDescriptor = new SemanticDomainDefinition__BehaviorDescriptor();
  private final BHDescriptor myFieldDefinition__BehaviorDescriptor = new FieldDefinition__BehaviorDescriptor();
  private final BHDescriptor myIElement__BehaviorDescriptor = new IElement__BehaviorDescriptor();
  private final BHDescriptor myIStructure__BehaviorDescriptor = new IStructure__BehaviorDescriptor();
  private final BHDescriptor myStructureDefinition__BehaviorDescriptor = new StructureDefinition__BehaviorDescriptor();
  private final BHDescriptor myField__BehaviorDescriptor = new Field__BehaviorDescriptor();
  private final BHDescriptor myDataDictionary__BehaviorDescriptor = new DataDictionary__BehaviorDescriptor();

  public BehaviorAspectDescriptor() {
  }

  @Nullable
  public BHDescriptor getDescriptor(@NotNull SAbstractConcept concept) {
    SAbstractConcept cncpt = concept;
    switch (conceptIndex.index(cncpt)) {
      case 0:
        return myDataDictionary__BehaviorDescriptor;
      case 1:
        return myField__BehaviorDescriptor;
      case 2:
        return myFieldDefinition__BehaviorDescriptor;
      case 3:
        return myIElement__BehaviorDescriptor;
      case 4:
        return myIStructure__BehaviorDescriptor;
      case 5:
        return mySemanticDomainDefinition__BehaviorDescriptor;
      case 6:
        return myStructure__BehaviorDescriptor;
      case 7:
        return myStructureDefinition__BehaviorDescriptor;
      default:
    }
    return null;
  }
  private static final ConceptSwitchIndex conceptIndex = new ConceptSwitchIndexBuilder().put(MetaIdFactory.conceptId(0xc2fcd0fd4f134552L, 0x8306bb0d4f1a7057L, 0x4a7b14560686268fL), MetaIdFactory.conceptId(0xc2fcd0fd4f134552L, 0x8306bb0d4f1a7057L, 0x4a7b145606822015L), MetaIdFactory.conceptId(0xc2fcd0fd4f134552L, 0x8306bb0d4f1a7057L, 0x4a7b145606795ab4L), MetaIdFactory.conceptId(0xc2fcd0fd4f134552L, 0x8306bb0d4f1a7057L, 0x4a7b1456067980e5L), MetaIdFactory.conceptId(0xc2fcd0fd4f134552L, 0x8306bb0d4f1a7057L, 0x4a7b1456067981e8L), MetaIdFactory.conceptId(0xc2fcd0fd4f134552L, 0x8306bb0d4f1a7057L, 0x4a7b145606795aa3L), MetaIdFactory.conceptId(0xc2fcd0fd4f134552L, 0x8306bb0d4f1a7057L, 0xed6c1e7ab041105L), MetaIdFactory.conceptId(0xc2fcd0fd4f134552L, 0x8306bb0d4f1a7057L, 0x4a7b1456067f55f1L)).seal();
}
